name: Auto-deploy React App

on:
    push:
        branches: ["main"]
        paths:
            - "Apps/**"
            - ".github/workflows/auto_deploy.yml"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 19.x
                  cache: "npm"
                  cache-dependency-path: ./Apps/01-first_app/package-lock.json

            - name: Install pkgs and build.
              run: |
                  cd ./Apps/01-first_app/;
                  npm ci;
                  npm run build --if-present;

            - name: Deploy app to GH pages.
              run: |
                  git config --global user.name $user_name
                  git config --global user.email $user_email
                  git config remote.origin.url 'https://${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git'
                  cd ./Apps/01-first_app/;

                  npm run deploy
              env:
                  user_name: "ArielMAJ"
                  user_email: "ariel.maj@hotmail.comm"